joint1 :   # XM-430
   return_delay_time     : 0    
   operating_mode        : 3     
   goal_current          : 0
   homing_offset         : 0

joint2 :   # XM-430
   return_delay_time     : 0   
   operating_mode        : 3     
   goal_current          : 0
   homing_offset         : 0

joint3 :   # XM-430
   return_delay_time     : 0    
   operating_mode        : 3
   goal_current          : 0
   homing_offset         : 0

joint4 :   # XM-430
   return_delay_time     : 0    
   operating_mode        : 3     
   goal_current          : 0
   homing_offset         : 0

joint5 :   # XM-430
   return_delay_time     : 0    
   operating_mode        : 3     
   goal_current          : 0
   homing_offset         : 0

joint6 :   # XM-430
   return_delay_time     : 0    
   operating_mode        : 3     
   goal_current          : 0
   homing_offset         : 0

joint7 :   # XM-430
   return_delay_time     : 0    
   operating_mode        : 3     
   goal_current          : 0
   homing_offset         : 0

grip_joint :   # XM-430
   return_delay_time     : 0    
   operating_mode        : 3     
   goal_current          : 0
   homing_offset         : -636
