mov_time : 3.0     # movement time
tar_pose :
  joint1 : 0.0	   # joint 1
  joint2 : -74.41  # joint 2
  joint3 : 0.0     # joint 3
  joint4 : -18.78  # joint 3
  joint5 : 0.0	   # joint 4
  joint6 : -55.63  # joint 5
  joint7 : 0.0	   # joint 6
