joint1:
  d_gain: 0.01
  i_gain: 0.0001
  p_gain: 3.5
joint2:
  d_gain: 0.01
  i_gain: 0.0001
  p_gain: 7.7
joint3:
  d_gain: 0.01
  i_gain: 0.0001
  p_gain: 7
joint4:
  d_gain: 0.01
  i_gain: 0.0001
  p_gain: 1.4
joint5:
  d_gain: 0.01
  i_gain: 0.0001
  p_gain: 1.4
joint6:
  d_gain: 0.01
  i_gain: 0.0001
  p_gain: 0.7